# Generated by Django 5.2.3 on 2025-07-25 05:00

import django.db.models.deletion
from django.db import migrations, models


def set_default_standard(apps, schema_editor):
    """Update existing TrackerForm records to use the first available Standard"""
    TrackerForm = apps.get_model('shared', 'TrackerForm')
    Standard = apps.get_model('shared', 'Standard')
    
    # Get the first standard
    first_standard = Standard.objects.order_by('standard_id').first()
    if first_standard:
        # Update all TrackerForms without a standard
        TrackerForm.objects.filter(standard__isnull=True).update(standard=first_standard)


def reverse_set_default_standard(apps, schema_editor):
    """Reverse operation - set standard to NULL"""
    TrackerForm = apps.get_model('shared', 'TrackerForm')
    TrackerForm.objects.all().update(standard=None)


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0015_remove_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerform',
            name='standard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracker_forms', to='shared.standard'),
        ),
        migrations.RunPython(set_default_standard, reverse_set_default_standard),
        migrations.AlterField(
            model_name='trackerform',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_forms', to='shared.standard'),
        ),
    ]
