# Generated by Django 5.2.4 on 2025-08-03 16:07

import django.utils.timezone
from django.db import migrations, models


def drop_follow_table(apps, schema_editor):
    """Drop shared_follow table if it exists"""
    # Use schema_editor to safely drop table
    try:
        schema_editor.execute("DROP TABLE IF EXISTS shared_follow CASCADE;")
    except Exception:
        # Table already doesn't exist
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0027_merge_20250803_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        # Clean up legacy Follow table if it exists
        migrations.RunPython(drop_follow_table, migrations.RunPython.noop),
    ]
