# Generated by Django 5.2.4

from django.db import migrations, models
from django.utils import timezone


def ensure_post_created_at(apps, schema_editor):
    """Ensure created_at column exists and drop legacy Follow table"""
    # Add column if missing (idempotent)
    try:
        schema_editor.execute(
            "ALTER TABLE shared_post ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;"
        )
    except Exception:
        pass
    
    # Drop old Follow table if it still exists (idempotent)
    try:
        schema_editor.execute("DROP TABLE IF EXISTS shared_follow CASCADE;")
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0028_create_default_tracker_form'),
    ]

    operations = [
        # Do DB-only fixes in an idempotent way
        migrations.RunPython(ensure_post_created_at, migrations.RunPython.noop),
        
        # Keep your original field change (safe to run twice if identical)
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
