# Generated by Django 5.2.4 on 2025-08-06 14:29

from django.db import migrations, models


def drop_follow_table(apps, schema_editor):
    """Drop shared_follow table if it exists"""
    try:
        schema_editor.execute("DROP TABLE IF EXISTS shared_follow CASCADE;")
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0028_create_default_tracker_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ojt_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        # Clean up legacy Follow table
        migrations.RunPython(drop_follow_table, migrations.RunPython.noop),
    ]
