# Generated by Django 5.2.3 on 2025-09-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0044_post_created_at_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojtinfo',
            name='ojt_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='ojtinfo',
            index=models.Index(fields=['ojt_start_date'], name='shared_ojti_ojt_sta_18ce2c_idx'),
        ),
    ]
