# Generated by Django 5.2.3 on 2025-09-13 16:28

from django.db import migrations


def update_questions(apps, schema_editor):
    """Update question 27 and add question 28"""
    Question = apps.get_model('shared', 'Question')
    QuestionCategory = apps.get_model('shared', 'QuestionCategory')
    
    # Find the "PART III : EMPLOYMENT STATUS" category
    try:
        employment_category = QuestionCategory.objects.get(title='PART III : EMPLOYMENT STATUS')
        
        # Update question 27: Change from Private/Government to Public/Private
        question_27 = Question.objects.filter(
            category=employment_category,
            text='Current Sector of your Job'
        ).first()
        
        if question_27:
            question_27.options = ['Public', 'Private']
            question_27.save()
            print(f"Updated question 27: {question_27.text}")
        
        # Add new question 28: Employment Sector (Local/International)
        # Insert it after question 27 (Current Sector of your Job)
        new_question = Question.objects.create(
            category=employment_category,
            text='Employment Sector',
            type='radio',
            options=['Local', 'International']
        )
        print(f"Added question 28: {new_question.text}")
        
        # Update all subsequent questions' text to reflect new numbering
        # Questions that come after the new question 28 need to be renumbered
        subsequent_questions = Question.objects.filter(
            category=employment_category,
            id__gt=new_question.id
        ).order_by('id')
        
        # The questions that need renumbering are:
        # - "How long have you been employed?" (was 28, now 29)
        # - "Current Salary range" (was 29, now 30) 
        # - "Have you received any awards..." (was 30, now 31)
        # - "Supporting Documents for awards..." (was 31, now 32)
        # - "Employment Supporting Document..." (was 32, now 33)
        
        # Note: We don't need to change the text, just the order in the database
        # The frontend will display them in the correct order based on their ID
        
    except QuestionCategory.DoesNotExist:
        print("PART III : EMPLOYMENT STATUS category not found")


def reverse_update_questions(apps, schema_editor):
    """Reverse the changes"""
    Question = apps.get_model('shared', 'Question')
    QuestionCategory = apps.get_model('shared', 'QuestionCategory')
    
    try:
        employment_category = QuestionCategory.objects.get(title='PART III : EMPLOYMENT STATUS')
        
        # Revert question 27 back to Private/Government
        question_27 = Question.objects.filter(
            category=employment_category,
            text='Current Sector of your Job'
        ).first()
        
        if question_27:
            question_27.options = ['Private', 'Government']
            question_27.save()
        
        # Remove question 28
        Question.objects.filter(
            category=employment_category,
            text='Employment Sector'
        ).delete()
        
    except QuestionCategory.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0046_add_sector_scope_fields'),
    ]

    operations = [
        migrations.RunPython(update_questions, reverse_update_questions),
    ]
