# Generated by Django 5.2.3 on 2025-09-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0045_ojtinfo_ojt_start_date_and_more'),
        ('shared', '0045_postimagedisabled_delete_postimage'),
        ('shared', '0047_update_question_27_and_add_28'),
    ]

    operations = [
    ]
