# Generated by Django 5.2.3 on 2025-09-17 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0048_merge_20250916_1856'),
        ('shared', '0049_merge_20250916_1724'),
    ]

    operations = [
    ]
