# Generated by Django 5.2.3 on 2025-09-19 07:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0050_merge_20250917_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='like',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_title',
        ),
        migrations.AddField(
            model_name='forum',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forum',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forum_images/'),
        ),
        migrations.AddField(
            model_name='forum',
            name='post_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='shared.postcategory'),
        ),
        migrations.AddField(
            model_name='forum',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('forum_comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_content', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shared.forum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shared_forumcomment',
            },
        ),
        migrations.CreateModel(
            name='ForumLike',
            fields=[
                ('forum_like_id', models.AutoField(primary_key=True, serialize=False)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='shared.forum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shared_forumlike',
                'unique_together': {('forum', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ForumRepost',
            fields=[
                ('forum_repost_id', models.AutoField(primary_key=True, serialize=False)),
                ('repost_date', models.DateTimeField(auto_now_add=True)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='shared.forum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_reposts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shared_forumrepost',
            },
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
