# Generated by Django 5.2.3 on 2025-09-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0055_set_db_default_date_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='date_send'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, db_column='message_content', default=''),
        ),
    ]
