# Generated by Django 5.2.3 on 2025-09-28 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0058_relax_messageattachment_message_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='repost',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RepostComment',
            fields=[
                ('repost_comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_content', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('repost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shared.repost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repost_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shared_repostcomment',
            },
        ),
        migrations.CreateModel(
            name='RepostLike',
            fields=[
                ('repost_like_id', models.AutoField(primary_key=True, serialize=False)),
                ('repost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='shared.repost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repost_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shared_repostlike',
                'unique_together': {('repost', 'user')},
            },
        ),
    ]
