# Generated by Django 5.2.3 on 2025-09-28 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0059_repost_caption_repostcomment_repostlike'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='forum',
            table='shared_forum',
        ),
    ]
