# Generated by Django 5.2.3 on 2025-10-01 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0066_alter_forumlike_unique_together_and_more'),
    ]

    operations = [
        # Skip deleting ForumRepost as it doesn't exist in database
        migrations.AddField(
            model_name='repost',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_reposts', to='shared.forum'),
        ),
        migrations.AlterField(
            model_name='repost',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_reposts', to='shared.post'),
        ),
        migrations.AddConstraint(
            model_name='repost',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('forum__isnull', True), ('post__isnull', False)), models.Q(('forum__isnull', False), ('post__isnull', True)), _connector='OR'), name='repost_post_or_forum_not_both'),
        ),
    ]
