# Generated by Django 5.2.3 on 2025-10-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0069_postimage_delete_forumrepost'),
    ]

    operations = [
    ]
