# Generated by Django 5.2.3 on 2025-10-02 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0073_donationrequest_donationimage_delete_forumrepost'),
    ]

    operations = [
        # Removed ForumRepost deletion as the table doesn't exist
    ]
