# Generated by Django 5.2.3 on 2025-10-02 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0077_remove_redundant_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumrepost',
            name='forum',
        ),
        migrations.RemoveField(
            model_name='forumrepost',
            name='user',
        ),
        migrations.DeleteModel(
            name='PostImageDisabled',
        ),
        migrations.RemoveConstraint(
            model_name='comment',
            name='comment_post_or_forum_not_both',
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='like_post_or_forum_not_both',
        ),
        migrations.RemoveConstraint(
            model_name='repost',
            name='repost_post_or_forum_not_both',
        ),
        migrations.AddField(
            model_name='comment',
            name='repost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repost_comments', to='shared.repost'),
        ),
        migrations.AddField(
            model_name='like',
            name='repost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repost_likes', to='shared.repost'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('donation_request__isnull', True), ('forum__isnull', True), ('post__isnull', False), ('repost__isnull', True)), models.Q(('donation_request__isnull', True), ('forum__isnull', False), ('post__isnull', True), ('repost__isnull', True)), models.Q(('donation_request__isnull', False), ('forum__isnull', True), ('post__isnull', True), ('repost__isnull', True)), models.Q(('donation_request__isnull', True), ('forum__isnull', True), ('post__isnull', True), ('repost__isnull', False)), _connector='OR'), name='comment_one_content_type_only'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('donation_request__isnull', True), ('forum__isnull', True), ('post__isnull', False), ('repost__isnull', True)), models.Q(('donation_request__isnull', True), ('forum__isnull', False), ('post__isnull', True), ('repost__isnull', True)), models.Q(('donation_request__isnull', False), ('forum__isnull', True), ('post__isnull', True), ('repost__isnull', True)), models.Q(('donation_request__isnull', True), ('forum__isnull', True), ('post__isnull', True), ('repost__isnull', False)), _connector='OR'), name='like_one_content_type_only'),
        ),
        migrations.AddConstraint(
            model_name='repost',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('donation_request__isnull', True), ('forum__isnull', True), ('post__isnull', False)), models.Q(('donation_request__isnull', True), ('forum__isnull', False), ('post__isnull', True)), models.Q(('donation_request__isnull', False), ('forum__isnull', True), ('post__isnull', True)), _connector='OR'), name='repost_one_content_type_only'),
        ),

    ]
