# Generated by Django 5.2.3 on 2025-10-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0078_remove_forumrepost_forum_remove_forumrepost_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForumRepost',
        ),
    ]
