# Generated by Django 5.2.3 on 2025-10-02 16:55

from django.db import migrations, models
from django.db.models import Q, CheckConstraint


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0080_auto_20251003_0041'),
    ]

    operations = [
        # Remove old constraints
        migrations.RemoveConstraint(
            model_name='like',
            name='like_post_or_forum_not_both',
        ),
        migrations.RemoveConstraint(
            model_name='comment',
            name='comment_post_or_forum_not_both',
        ),
        # Add new constraint for Like - exactly one content type
        migrations.AddConstraint(
            model_name='like',
            constraint=CheckConstraint(
                check=(
                    Q(post__isnull=False, forum__isnull=True, donation_request__isnull=True, repost__isnull=True) |
                    Q(post__isnull=True, forum__isnull=False, donation_request__isnull=True, repost__isnull=True) |
                    Q(post__isnull=True, forum__isnull=True, donation_request__isnull=False, repost__isnull=True) |
                    Q(post__isnull=True, forum__isnull=True, donation_request__isnull=True, repost__isnull=False)
                ),
                name='like_one_content_type_only',
            ),
        ),
        # Add new constraint for Comment - exactly one content type
        migrations.AddConstraint(
            model_name='comment',
            constraint=CheckConstraint(
                check=(
                    Q(post__isnull=False, forum__isnull=True, donation_request__isnull=True, repost__isnull=True) |
                    Q(post__isnull=True, forum__isnull=False, donation_request__isnull=True, repost__isnull=True) |
                    Q(post__isnull=True, forum__isnull=True, donation_request__isnull=False, repost__isnull=True) |
                    Q(post__isnull=True, forum__isnull=True, donation_request__isnull=True, repost__isnull=False)
                ),
                name='comment_one_content_type_only',
            ),
        ),
    ]
