# Generated by Django 5.2.3 on 2025-10-03 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0082_fix_repost_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImageDisabled',
            fields=[
                ('post_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='comment',
            name='comment_one_content_type_only',
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='like_one_content_type_only',
        ),
        migrations.RemoveField(
            model_name='question',
            name='required',
        ),
        migrations.AlterField(
            model_name='comment',
            name='repost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shared.repost'),
        ),
        migrations.AlterField(
            model_name='like',
            name='repost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='shared.repost'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('donation_request__isnull', True), ('forum__isnull', True), ('post__isnull', False), ('repost__isnull', True)), models.Q(('donation_request__isnull', True), ('forum__isnull', False), ('post__isnull', True), ('repost__isnull', True)), models.Q(('donation_request__isnull', True), ('forum__isnull', True), ('post__isnull', True), ('repost__isnull', False)), models.Q(('donation_request__isnull', False), ('forum__isnull', True), ('post__isnull', True), ('repost__isnull', True)), _connector='OR'), name='comment_one_content_type_only'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('donation_request__isnull', True), ('forum__isnull', True), ('post__isnull', False), ('repost__isnull', True)), models.Q(('donation_request__isnull', True), ('forum__isnull', False), ('post__isnull', True), ('repost__isnull', True)), models.Q(('donation_request__isnull', True), ('forum__isnull', True), ('post__isnull', True), ('repost__isnull', False)), models.Q(('donation_request__isnull', False), ('forum__isnull', True), ('post__isnull', True), ('repost__isnull', True)), _connector='OR'), name='like_one_content_type_only'),
        ),
    ]
