# Generated by Django 5.2.3 on 2025-10-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0093_add_cross_program_alignment_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employmenthistory',
            name='shared_empl_absorbe_idx',
        ),
        migrations.RemoveIndex(
            model_name='ojtinfo',
            name='shared_ojti_ojt_sta_idx',
        ),
        migrations.RemoveIndex(
            model_name='trackerdata',
            name='shared_trac_q_secto_idx',
        ),
        migrations.RemoveIndex(
            model_name='trackerdata',
            name='shared_trac_q_scope_idx',
        ),
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
