# Generated by Django 5.2.3 on 2025-10-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0094_add_question_required_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenthistory',
            name='scope_current',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
