# Generated by Django 5.2.3 on 2025-10-09 11:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0095_add_scope_current_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatorProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('BSIT', 'Bachelor of Science in Information Technology'), ('BSIS', 'Bachelor of Science in Information Systems'), ('BIT-CT', 'Bachelor of Industrial Technology - Computer Technology')], max_length=10)),
                ('department', models.CharField(default='Computer Studies', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_program', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['program'], name='shared_coor_program_7ffc5d_idx')],
                'unique_together': {('program',)},
            },
        ),
    ]
