# Generated by Django 5.2.3 on 2025-10-11 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0083_add_missing_repost_fields'),
        ('shared', '0096_add_coordinator_program_model'),
    ]

    operations = [
    ]
