# Generated by Django 5.2.3 on 2025-10-11 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0097_merge_20251012_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='coordinatorprogram',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='coordinatorprogram',
            name='coordinator',
        ),
        migrations.RemoveIndex(
            model_name='simplecomptechjob',
            name='simplecomptechjob_job_title_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='simpleinfosystemjob',
            name='simpleinfosystemjob_job_title_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='simpleinfotechjob',
            name='simpleinfotechjob_job_title_trgm_idx',
        ),
        migrations.RemoveField(
            model_name='message',
            name='date_send',
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='company_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ojtimport',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ojtinfo',
            name='is_sent_to_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ojtinfo',
            name='sent_to_admin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, db_column='message_content', default=''),
        ),
        migrations.AddField(
            model_name='recentsearch',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_searches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recentsearch',
            name='searched_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appears_in_recent_searches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CoordinatorProgram',
        ),
        migrations.AlterUniqueTogether(
            name='recentsearch',
            unique_together={('owner', 'searched_user')},
        ),
    ]
