# Generated by Django 5.2.3 on 2025-10-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0098_recentsearch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenthistory',
            name='company_email',
            field=models.EmailField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='company_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
