# Generated by Django 5.2.3 on 2025-10-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0099_add_missing_employment_fields'),
    ]

    operations = [
        # Add missing OJTInfo fields from migration 0098
        migrations.AddField(
            model_name='ojtinfo',
            name='is_sent_to_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ojtinfo',
            name='sent_to_admin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # Add missing OJTImport field from migration 0098
        migrations.AddField(
            model_name='ojtimport',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        # Note: 'required' field already exists, so we skip it
    ]
