"""
Auto-generated tracker questions seed file.
Generated on: 2025-10-30 00:42:15

This file contains the exact questions from the database.
DO NOT EDIT THIS FILE MANUALLY - it will be overwritten when you run:
    python manage.py export_tracker_questions

To use this file to seed questions in a new database, run:
    python manage.py seed_tracker_questions
"""

from apps.shared.models import QuestionCategory, Question


# Categories and questions exported from database
CATEGORIES_DATA = [
        {
            'title': 'INTRODUCTION',
            'description': 'To our Dear Graduates,\nKindly complete this questionnaire accurately and truthfully. Your responses will be used for research purposes to assess employability and, ultimately, improve the curriculum programs offered at Cebu Technological University (CTU). Rest assured that your answers to this survey will be treated with the utmost confidentiality. Thank you very much!\nIf you have any questions, you may contact the office of the Alumni Director through email address gts@ctu.edu.ph or Contact no: (032) 402 4060.',
            'order': 0,
            'questions': [
                {
                    'text': 'Year Graduated',
                    'type': 'text',
                    'options': [],
                    'required': True,
                    'order': 0,
                },
                {
                    'text': 'Program Graduated',
                    'type': 'text',
                    'options': [],
                    'required': True,
                    'order': 1,
                },
                {
                    'text': 'Email',
                    'type': 'text',
                    'options': [],
                    'required': True,
                    'order': 2,
                }
            ]
        },
        {
            'title': 'PART I : PERSONAL PROFILE',
            'description': 'N/A if not applicable',
            'order': 0,
            'questions': [
                {
                    'text': 'Last Name',
                    'type': 'text',
                    'options': [],
                    'required': True,
                    'order': 0,
                },
                {
                    'text': 'First Name',
                    'type': 'text',
                    'options': [],
                    'required': True,
                    'order': 1,
                },
                {
                    'text': 'Middle Name (If none write N/A)',
                    'type': 'text',
                    'options': [],
                    'required': True,
                    'order': 2,
                },
                {
                    'text': 'Age',
                    'type': 'text',
                    'options': [],
                    'required': True,
                    'order': 3,
                },
                {
                    'text': 'Birthdate',
                    'type': 'text',
                    'options': [],
                    'required': True,
                    'order': 4,
                },
                {
                    'text': 'Landline or Mobile Number',
                    'type': 'text',
                    'options': [],
                    'required': True,
                    'order': 5,
                },
                {
                    'text': 'Social Media Account Link (e.g https://www.facebook.com/aboloc)',
                    'type': 'text',
                    'options': [],
                    'required': True,
                    'order': 6,
                },
                {
                    'text': 'Complete Current Address',
                    'type': 'text',
                    'options': [],
                    'required': True,
                    'order': 7,
                },
                {
                    'text': 'Complete Home Address',
                    'type': 'text',
                    'options': [],
                    'required': True,
                    'order': 8,
                },
                {
                    'text': 'Civil Status',
                    'type': 'multiple',
                    'options': ["Single", "Married", "Widow"],
                    'required': True,
                    'order': 9,
                }
            ]
        },
        {
            'title': 'PART II : EMPLOYMENT HISTORY',
            'description': 'N/A if not applicable',
            'order': 0,
            'questions': [
                {
                    'text': 'Name of your organization/employer (1st employer right after graduation)',
                    'type': 'text',
                    'options': [],
                    'required': True,
                    'order': 0,
                },
                {
                    'text': 'Date Hired (1st employer right after graduation)',
                    'type': 'text',
                    'options': [],
                    'required': True,
                    'order': 1,
                },
                {
                    'text': 'Position (1st employer right after graduation) N/A if not applicable',
                    'type': 'text',
                    'options': [],
                    'required': True,
                    'order': 2,
                },
                {
                    'text': 'Status of your employment (1st employer right after graduation)',
                    'type': 'multiple',
                    'options': ["Permanent", "Temporary"],
                    'required': True,
                    'order': 3,
                },
                {
                    'text': 'Company Address (1st employer right after graduation)',
                    'type': 'text',
                    'options': [],
                    'required': True,
                    'order': 4,
                },
                {
                    'text': 'Sector (1st employer right after graduation)',
                    'type': 'radio',
                    'options': ["Private", "Government"],
                    'required': True,
                    'order': 5,
                },
                {
                    'text': 'First Employment Supporting Document',
                    'type': 'file',
                    'options': [],
                    'required': True,
                    'order': 6,
                },
                {
                    'text': 'Are you PRESENTLY employed ?',
                    'type': 'radio',
                    'options': ["Yes", "No"],
                    'required': True,
                    'order': 7,
                },
                {
                    'text': 'Did you pursue futher study?',
                    'type': 'radio',
                    'options': ["Yes", "No"],
                    'required': True,
                    'order': 8,
                }
            ]
        },
        {
            'title': 'PART III : EMPLOYMENT STATUS',
            'description': 'N/A if not applicable',
            'order': 0,
            'questions': [
                {
                    'text': 'Are you employed by a company/organization or are you self employed ?',
                    'type': 'multiple',
                    'options': ["Employed by a company/organization", "Self-employed", "Freelance/Contract-based"],
                    'required': True,
                    'order': 0,
                },
                {
                    'text': 'Status of your current employment',
                    'type': 'multiple',
                    'options': ["Permanent", "Temporary"],
                    'required': True,
                    'order': 1,
                },
                {
                    'text': 'Current Company Name',
                    'type': 'text',
                    'options': [],
                    'required': True,
                    'order': 2,
                },
                {
                    'text': 'Current Position',
                    'type': 'text',
                    'options': [],
                    'required': True,
                    'order': 3,
                },
                {
                    'text': 'Current Sector of your Job',
                    'type': 'radio',
                    'options': ["Public", "Private"],
                    'required': True,
                    'order': 4,
                },
                {
                    'text': 'Current Scope of your Job',
                    'type': 'radio',
                    'options': ["Local", "International"],
                    'required': True,
                    'order': 5,
                },
                {
                    'text': 'How long have you been employed?',
                    'type': 'text',
                    'options': [],
                    'required': True,
                    'order': 6,
                },
                {
                    'text': 'Current Salary range',
                    'type': 'text',
                    'options': [],
                    'required': True,
                    'order': 7,
                },
                {
                    'text': 'Have you received any awards or recognition during your employment?',
                    'type': 'radio',
                    'options': ["Yes", "No"],
                    'required': True,
                    'order': 8,
                },
                {
                    'text': 'Supporting Documents for awards/recognition',
                    'type': 'file',
                    'options': [],
                    'required': True,
                    'order': 9,
                },
                {
                    'text': 'Employment Supporting Document(Current)',
                    'type': 'file',
                    'options': [],
                    'required': True,
                    'order': 10,
                },
                {
                    'text': 'Employment Sector',
                    'type': 'radio',
                    'options': ["Local", "International"],
                    'required': True,
                    'order': 11,
                }
            ]
        },
        {
            'title': 'IF UNEMPLOYED',
            'description': '',
            'order': 0,
            'questions': [
                {
                    'text': 'Reason for unemployment',
                    'type': 'checkbox',
                    'options': ["Family concerns and the decision not to find a job", "Health-related reasons", "Lack of work experience", "No job opportunity", "Did not look for a job", "Seeking employment", "For further study"],
                    'required': False,
                    'order': 0,
                }
            ]
        },
        {
            'title': 'PART IV : FURTHER STUDY',
            'description': 'N/A if not applicable',
            'order': 0,
            'questions': [
                {
                    'text': 'Date Started',
                    'type': 'text',
                    'options': [],
                    'required': True,
                    'order': 0,
                },
                {
                    'text': 'Please specify post graduate/degree',
                    'type': 'text',
                    'options': [],
                    'required': True,
                    'order': 1,
                },
                {
                    'text': 'Name of Institution/University',
                    'type': 'text',
                    'options': [],
                    'required': True,
                    'order': 2,
                },
                {
                    'text': 'Total number of units obtain',
                    'type': 'text',
                    'options': [],
                    'required': True,
                    'order': 3,
                }
            ]
        }
    ]


def seed_tracker_questions(apps=None, schema_editor=None):
    """
    Seed tracker questions from exported data.
    Can be used as a migration function or standalone.
    
    Returns:
        tuple: (list of created categories, list of created questions)
    """
    if apps:
        # Running as a migration
        QuestionCategory = apps.get_model('shared', 'QuestionCategory')
        Question = apps.get_model('shared', 'Question')
        use_migration_mode = True
    else:
        # Running standalone
        from apps.shared.models import QuestionCategory, Question
        use_migration_mode = False

    # Delete existing questions and categories to ensure clean state
    if not use_migration_mode:
        Question.objects.all().delete()
        QuestionCategory.objects.all().delete()

    created_categories = []
    created_questions = []

    for cat_data in CATEGORIES_DATA:
        # Create category
        category = QuestionCategory.objects.create(
            title=cat_data['title'],
            description=cat_data['description'],
            order=cat_data.get('order', 0)
        )
        created_categories.append(category)

        # Create questions for this category
        for q_data in cat_data['questions']:
            question = Question.objects.create(
                category=category,
                text=q_data['text'],
                type=q_data['type'],
                options=q_data['options'] if q_data['options'] else None,
                required=q_data.get('required', False),
                order=q_data.get('order', 0)
            )
            created_questions.append(question)

    return created_categories, created_questions


def unseed_tracker_questions(apps, schema_editor):
    """Remove all tracker questions (for migration rollback)"""
    QuestionCategory = apps.get_model('shared', 'QuestionCategory')
    QuestionCategory.objects.all().delete()

