<<<<<<< HEAD
# Generated by Django 5.2.3 on 2025-10-11 19:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
=======
# Generated by Django 5.2.3 on 2025-06-21 08:01

import django.db.models.deletion
>>>>>>> 746e601016fd6b6113a8116f65f35a08788c789a
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='PostImageDisabled',
            fields=[
                ('post_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
            ],
            options={
                'managed': False,
            },
=======
            name='Aacup',
            fields=[
                ('aacup_id', models.AutoField(primary_key=True, serialize=False)),
            ],
>>>>>>> 746e601016fd6b6113a8116f65f35a08788c789a
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('account_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin', models.BooleanField()),
                ('peso', models.BooleanField()),
                ('user', models.BooleanField()),
                ('coordinator', models.BooleanField()),
<<<<<<< HEAD
                ('ojt', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OJTImport',
            fields=[
                ('import_id', models.AutoField(primary_key=True, serialize=False)),
                ('coordinator', models.CharField(max_length=100)),
                ('batch_year', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('records_imported', models.IntegerField(default=0)),
                ('status', models.CharField(default='Completed', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleCompTechJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleInfoSystemJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleInfoTechJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('acc_username', models.CharField(max_length=100, unique=True)),
                ('acc_password', models.CharField(blank=True, max_length=128, null=True)),
                ('user_status', models.CharField(max_length=50)),
                ('f_name', models.CharField(max_length=100)),
                ('m_name', models.CharField(blank=True, max_length=100, null=True)),
                ('l_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='shared.accounttype')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shared_conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('fulfilled', 'Fulfilled'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shared_donationrequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='donation_images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shared.donationrequest')),
            ],
            options={
                'db_table': 'shared_donationimage',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name_current', models.CharField(blank=True, max_length=255, null=True)),
                ('position_current', models.CharField(blank=True, max_length=255, null=True)),
                ('sector_current', models.CharField(blank=True, max_length=255, null=True)),
                ('scope_current', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_duration_current', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_current', models.CharField(blank=True, max_length=100, null=True)),
                ('date_started', models.DateField(blank=True, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('job_alignment_status', models.CharField(blank=True, default='not_aligned', max_length=50, null=True)),
                ('job_alignment_category', models.CharField(blank=True, max_length=100, null=True)),
                ('job_alignment_title', models.CharField(blank=True, max_length=255, null=True)),
                ('job_alignment_suggested_program', models.CharField(blank=True, help_text='Program suggested for cross-alignment', max_length=50, null=True)),
                ('job_alignment_original_program', models.CharField(blank=True, help_text='Original program of the graduate', max_length=50, null=True)),
                ('self_employed', models.BooleanField(default=False)),
                ('high_position', models.BooleanField(default=False)),
                ('absorbed', models.BooleanField(default=False)),
                ('awards_recognition_current', models.CharField(blank=True, max_length=255, null=True)),
                ('supporting_document_current', models.CharField(blank=True, max_length=255, null=True)),
                ('supporting_document_awards_recognition', models.CharField(blank=True, max_length=255, null=True)),
                ('unemployment_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('follow_id', models.AutoField(primary_key=True, serialize=False)),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shared_follow',
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('forum_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='forum_images/')),
                ('content', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='date_send')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forums', to=settings.AUTH_USER_MODEL)),
=======
            ],
        ),
        migrations.CreateModel(
            name='Ched',
            fields=[
                ('ched_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompTechJob',
            fields=[
                ('comp_tech_jobs_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('import_id', models.AutoField(primary_key=True, serialize=False)),
                ('import_year', models.IntegerField()),
                ('import_by', models.CharField(max_length=255)),
>>>>>>> 746e601016fd6b6113a8116f65f35a08788c789a
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('content', models.TextField(blank=True, db_column='message_content', default='')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('system', 'System')], default='text', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='shared.conversation')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shared_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='message_attachments/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='shared.message')),
            ],
            options={
                'db_table': 'shared_messageattachment',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notif_type', models.CharField(max_length=100)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('notifi_content', models.TextField()),
                ('notif_date', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OJTInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ojt_start_date', models.DateField(blank=True, null=True)),
                ('ojt_end_date', models.DateField(blank=True, null=True)),
                ('job_code', models.CharField(blank=True, max_length=20, null=True)),
                ('ojtstatus', models.CharField(blank=True, max_length=50, null=True)),
                ('is_sent_to_admin', models.BooleanField(default=False)),
                ('sent_to_admin_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ojt_info', to=settings.AUTH_USER_MODEL)),
=======
                ('sender_id', models.IntegerField()),
                ('receiver_id', models.IntegerField()),
                ('message_content', models.TextField()),
                ('date_send', models.DateTimeField()),
>>>>>>> 746e601016fd6b6113a8116f65f35a08788c789a
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('post_image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('post_content', models.TextField()),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='post_images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shared.post')),
            ],
            options={
                'db_table': 'shared_postimage',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('options', models.JSONField(blank=True, null=True)),
                ('required', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='shared.questioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_searches', to=settings.AUTH_USER_MODEL)),
                ('searched_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appears_in_recent_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Repost',
            fields=[
                ('repost_id', models.AutoField(primary_key=True, serialize=False)),
                ('repost_date', models.DateTimeField()),
                ('caption', models.TextField(blank=True, null=True)),
                ('donation_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_reposts', to='shared.donationrequest')),
                ('forum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_reposts', to='shared.forum')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_reposts', to='shared.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('donation_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_likes', to='shared.donationrequest')),
                ('forum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_likes', to='shared.forum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='shared.post')),
                ('repost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='shared.repost')),
            ],
        ),
=======
                ('post_title', models.CharField(max_length=255)),
                ('post_image', models.CharField(max_length=255)),
                ('post_content', models.TextField()),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('post_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('events', models.BooleanField()),
                ('announcements', models.BooleanField()),
                ('donation', models.BooleanField()),
                ('personal', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Qpro',
            fields=[
                ('qpro_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='InfoSystemJob',
            fields=[
                ('info_system_jobs_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('comp_tech_jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infosystemjob_comptechjobs', to='shared.comptechjob')),
            ],
        ),
        migrations.AddField(
            model_name='comptechjob',
            name='info_system_jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptechjob_infosystemjobs', to='shared.infosystemjob'),
        ),
        migrations.CreateModel(
            name='InfoTechJob',
            fields=[
                ('info_tech_jobs_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('comp_tech_jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infotechjob_comptechjobs', to='shared.comptechjob')),
                ('info_systems_jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infotechjob_infosystemjobs', to='shared.infosystemjob')),
            ],
        ),
        migrations.AddField(
            model_name='infosystemjob',
            name='info_tech_jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infosystemjob_infotechjobs', to='shared.infotechjob'),
        ),
        migrations.AddField(
            model_name='comptechjob',
            name='info_tech_jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptechjob_infotechjobs', to='shared.infotechjob'),
        ),
>>>>>>> 746e601016fd6b6113a8116f65f35a08788c789a
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_content', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField()),
<<<<<<< HEAD
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('donation_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_comments', to='shared.donationrequest')),
                ('forum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments', to='shared.forum')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='shared.post')),
                ('repost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shared.repost')),
            ],
        ),
        migrations.CreateModel(
            name='TrackerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_employment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('q_employment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('q_employment_permanent', models.CharField(blank=True, max_length=20, null=True)),
                ('q_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('q_current_position', models.CharField(blank=True, max_length=255, null=True)),
                ('q_job_sector', models.CharField(blank=True, max_length=50, null=True)),
                ('q_sector_current', models.CharField(blank=True, max_length=50, null=True)),
                ('q_scope_current', models.CharField(blank=True, max_length=50, null=True)),
                ('q_employment_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('q_salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('q_awards_received', models.CharField(blank=True, max_length=10, null=True)),
                ('q_awards_document', models.FileField(blank=True, null=True, upload_to='awards/')),
                ('q_employment_document', models.FileField(blank=True, null=True, upload_to='employment/')),
                ('q_unemployment_reason', models.JSONField(blank=True, null=True)),
                ('tracker_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('tracker_last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackerForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='CTU Alumni Tracker Form', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('accepting_responses', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='single_tracker_form')],
            },
        ),
        migrations.CreateModel(
            name='TrackerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackerFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('file', models.FileField(upload_to='tracker_uploads/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='shared.trackerresponse')),
            ],
        ),
        migrations.CreateModel(
            name='UserInitialPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_encrypted', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='initial_password', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('home_address', models.TextField(blank=True, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=50, null=True)),
                ('social_media', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('profile_bio', models.TextField(blank=True, null=True)),
                ('profile_resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_graduated', models.IntegerField(blank=True, null=True)),
                ('program', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pursue_further_study', models.CharField(blank=True, max_length=10, null=True)),
                ('q_pursue_study', models.CharField(blank=True, max_length=10, null=True)),
                ('q_study_start_date', models.DateField(blank=True, null=True)),
                ('q_post_graduate_degree', models.CharField(blank=True, max_length=255, null=True)),
                ('q_institution_name', models.CharField(blank=True, max_length=255, null=True)),
                ('q_units_obtained', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['year_graduated', 'program'], name='shared_acad_year_gr_544607_idx'), models.Index(fields=['pursue_further_study'], name='shared_acad_pursue__15a11a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_status'], name='shared_user_user_st_bb4796_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['acc_username'], name='shared_user_acc_use_90120a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['f_name', 'l_name'], name='shared_user_f_name_585897_idx'),
        ),
        migrations.AddIndex(
            model_name='employmenthistory',
            index=models.Index(fields=['company_name_current', 'position_current'], name='shared_empl_company_1f0ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='employmenthistory',
            index=models.Index(fields=['job_alignment_status'], name='shared_empl_job_ali_8945f3_idx'),
        ),
        migrations.AddIndex(
            model_name='employmenthistory',
            index=models.Index(fields=['self_employed', 'high_position'], name='shared_empl_self_em_ebd2af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='shared_mess_convers_108cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='shared_mess_sender__325014_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='shared_mess_is_read_1f93c2_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['message', 'uploaded_at'], name='shared_mess_message_426449_idx'),
        ),
        migrations.AddIndex(
            model_name='ojtinfo',
            index=models.Index(fields=['ojtstatus'], name='shared_ojti_ojtstat_911886_idx'),
        ),
        migrations.AddIndex(
            model_name='ojtinfo',
            index=models.Index(fields=['ojt_end_date'], name='shared_ojti_ojt_end_a1afc9_idx'),
        ),
        migrations.AddIndex(
            model_name='ojtinfo',
            index=models.Index(fields=['ojt_start_date'], name='shared_ojti_ojt_sta_18ce2c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recentsearch',
            unique_together={('owner', 'searched_user')},
        ),
        migrations.AddConstraint(
            model_name='repost',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('donation_request__isnull', True), ('forum__isnull', True), ('post__isnull', False)), models.Q(('donation_request__isnull', True), ('forum__isnull', False), ('post__isnull', True)), models.Q(('donation_request__isnull', False), ('forum__isnull', True), ('post__isnull', True)), _connector='OR'), name='repost_one_content_type_only'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('donation_request__isnull', True), ('forum__isnull', True), ('post__isnull', False), ('repost__isnull', True)), models.Q(('donation_request__isnull', True), ('forum__isnull', False), ('post__isnull', True), ('repost__isnull', True)), models.Q(('donation_request__isnull', True), ('forum__isnull', True), ('post__isnull', True), ('repost__isnull', False)), models.Q(('donation_request__isnull', False), ('forum__isnull', True), ('post__isnull', True), ('repost__isnull', True)), _connector='OR'), name='like_one_content_type_only'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('donation_request__isnull', True), ('forum__isnull', True), ('post__isnull', False), ('repost__isnull', True)), models.Q(('donation_request__isnull', True), ('forum__isnull', False), ('post__isnull', True), ('repost__isnull', True)), models.Q(('donation_request__isnull', True), ('forum__isnull', True), ('post__isnull', True), ('repost__isnull', False)), models.Q(('donation_request__isnull', False), ('forum__isnull', True), ('post__isnull', True), ('repost__isnull', True)), _connector='OR'), name='comment_one_content_type_only'),
        ),
        migrations.AddIndex(
            model_name='trackerdata',
            index=models.Index(fields=['q_employment_status'], name='shared_trac_q_emplo_676ad0_idx'),
        ),
        migrations.AddIndex(
            model_name='trackerdata',
            index=models.Index(fields=['tracker_submitted_at'], name='shared_trac_tracker_664665_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trackerresponse',
            unique_together={('user',)},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['civil_status'], name='shared_user_civil_s_911a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['age'], name='shared_user_age_d7322f_idx'),
=======
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shared.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='shared.postcategory'),
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('standard_id', models.AutoField(primary_key=True, serialize=False)),
                ('aacup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='shared.aacup')),
                ('ched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='shared.ched')),
                ('qpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='shared.qpro')),
            ],
        ),
        migrations.AddField(
            model_name='qpro',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qpros', to='shared.standard'),
        ),
        migrations.CreateModel(
            name='ExportedFile',
            fields=[
                ('exported_file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('exported_date', models.DateTimeField()),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exported_files', to='shared.standard')),
            ],
        ),
        migrations.AddField(
            model_name='ched',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheds', to='shared.standard'),
        ),
        migrations.AddField(
            model_name='aacup',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aacups', to='shared.standard'),
        ),
        migrations.CreateModel(
            name='Suc',
            fields=[
                ('suc_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_tech_jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suc_comptechjobs', to='shared.comptechjob')),
                ('info_system_jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suc_infosystemjobs', to='shared.infosystemjob')),
                ('info_tech_jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suc_infotechjobs', to='shared.infotechjob')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suc_sucs', to='shared.standard')),
            ],
        ),
        migrations.AddField(
            model_name='standard',
            name='suc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='shared.suc'),
        ),
        migrations.AddField(
            model_name='infotechjob',
            name='suc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infotechjob_sucs', to='shared.suc'),
        ),
        migrations.AddField(
            model_name='infosystemjob',
            name='suc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infosystemjob_sucs', to='shared.suc'),
        ),
        migrations.AddField(
            model_name='comptechjob',
            name='suc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptechjob_sucs', to='shared.suc'),
        ),
        migrations.CreateModel(
            name='TrackerForm',
            fields=[
                ('tracker_form_id', models.AutoField(primary_key=True, serialize=False)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_forms', to='shared.standard')),
            ],
        ),
        migrations.AddField(
            model_name='standard',
            name='tracker_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='shared.trackerform'),
        ),
        migrations.CreateModel(
            name='HighPosition',
            fields=[
                ('high_position_id', models.AutoField(primary_key=True, serialize=False)),
                ('aacup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_positions', to='shared.aacup')),
                ('tracker_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_positions', to='shared.trackerform')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('acc_username', models.CharField(max_length=100)),
                ('acc_password', models.DateField()),
                ('user_status', models.CharField(max_length=50)),
                ('f_name', models.CharField(max_length=100)),
                ('m_name', models.CharField(blank=True, max_length=100, null=True)),
                ('l_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('phone_num', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_bio', models.TextField(blank=True, null=True)),
                ('profile_resume', models.CharField(blank=True, max_length=255, null=True)),
                ('year_graduated', models.IntegerField(blank=True, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='shared.accounttype')),
                ('import_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='shared.import')),
            ],
        ),
        migrations.AddField(
            model_name='trackerform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_forms', to='shared.user'),
        ),
        migrations.CreateModel(
            name='Repost',
            fields=[
                ('repost_id', models.AutoField(primary_key=True, serialize=False)),
                ('repost_date', models.DateTimeField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='shared.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='shared.user')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='shared.user'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notif_type', models.CharField(max_length=100)),
                ('notifi_content', models.TextField()),
                ('notif_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shared.user')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='shared.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='shared.user')),
            ],
        ),
        migrations.AddField(
            model_name='import',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='shared.user'),
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('forum_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forums', to='shared.comment')),
                ('like', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forums', to='shared.like')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='shared.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='shared.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='shared.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='shared.user')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shared.user'),
>>>>>>> 746e601016fd6b6113a8116f65f35a08788c789a
        ),
    ]
