# Generated by Django 5.1.7 on 2025-09-21 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='donation_images/')),
                ('type', models.CharField(default='donation', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='date_send')),
                ('post_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_posts', to='shared.postcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shared_donation',
            },
        ),
        migrations.CreateModel(
            name='DonationComment',
            fields=[
                ('donation_comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shared.donation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shared_donationcomment',
            },
        ),
        migrations.CreateModel(
            name='DonationLike',
            fields=[
                ('donation_like_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='shared.donation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shared_donationlike',
            },
        ),
        migrations.CreateModel(
            name='DonationRepost',
            fields=[
                ('donation_repost_id', models.AutoField(primary_key=True, serialize=False)),
                ('repost_date', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='shared.donation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_reposts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shared_donationrepost',
            },
        ),
    ]
