# Generated by Django 5.2.3 on 2025-10-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0040_add_messaging_models'),
    ]

    operations = [
    ]
