# Generated by Django 5.2.3 on 2025-10-06 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0041_auto_20251004_2219'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='shared_mess_convers_108cd8_idx',
            old_name='shared_message_convers_created_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='shared_mess_sender__325014_idx',
            old_name='shared_message_sender_created_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='shared_mess_is_read_1f93c2_idx',
            old_name='shared_message_is_read_idx',
        ),
        migrations.RenameIndex(
            model_name='messageattachment',
            new_name='shared_mess_message_426449_idx',
            old_name='shared_messageattachment_message_uploaded_idx',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ojtimport',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ojtinfo',
            name='is_sent_to_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ojtinfo',
            name='sent_to_admin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, db_column='message_content', default=''),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='shared.message'),
        ),
    ]
