# Generated by Django 5.2.3 on 2025-10-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0042_add_sent_to_admin_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojtinfo',
            name='company_address',
            field=models.TextField(blank=True, help_text='Company address', null=True),
        ),
        migrations.AddField(
            model_name='ojtinfo',
            name='company_contact',
            field=models.CharField(blank=True, help_text='Company contact number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ojtinfo',
            name='company_email',
            field=models.EmailField(blank=True, help_text='Company email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ojtinfo',
            name='contact_person_name',
            field=models.CharField(blank=True, help_text='Full name of contact person', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ojtinfo',
            name='contact_person_position',
            field=models.CharField(blank=True, help_text='Position of contact person', max_length=255, null=True),
        ),
    ]
