# Generated by Django 5.2.3 on 2025-10-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0043_add_company_profile_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ojtinfo',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='ojtinfo',
            name='company_contact',
        ),
        migrations.RemoveField(
            model_name='ojtinfo',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='ojtinfo',
            name='contact_person_name',
        ),
        migrations.RemoveField(
            model_name='ojtinfo',
            name='contact_person_position',
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='company_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
