# Generated by Django 5.2.3 on 2025-09-08 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0043_rename_shared_message_convers_created_idx_shared_mess_convers_108cd8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('post_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='post_images/')),
                ('image_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shared.post')),
            ],
            options={
                'ordering': ['image_order', 'created_at'],
                'indexes': [models.Index(fields=['post', 'image_order'], name='shared_post_post_id_783b5b_idx')],
            },
        ),
    ]
