# Generated by Django 5.2.3 on 2025-09-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0044_post_created_at_postimage'),
    ]

    operations = [
    ]
