# Generated by Django 5.2.3 on 2025-09-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0044_post_created_at_postimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImageDisabled',
            fields=[
                ('post_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
