# Generated by Django 5.2.3 on 2025-09-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # The original parent '0044_post_created_at' does not exist.
        # Depend only on the valid head to fix migration graph.
        ('shared', '0044_post_created_at_postimage'),
    ]

    operations = [
    ]
