# Generated by Django 5.2.3 on 2025-09-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0045_merge_20250909_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImageDisabled',
            fields=[
                ('post_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='trackerdata',
            name='q_scope_current',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trackerdata',
            name='q_sector_current',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        # migrations.DeleteModel(
        #     name='PostImage',
        # ),
    ]
