# Generated by Django 5.2.3 on 2025-09-22 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
    ]
