# Generated by Django 5.2.3 on 2025-09-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0044_post_created_at_v1'),
        ('shared', '0047_update_question_27_and_add_28'),
    ]

    operations = [
    ]
