# Generated by Django 5.2.3 on 2025-09-17 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0045_ojtinfo_ojt_start_date_and_more'),
    ]

    operations = [
    ]
