# Generated by Django 5.2.3 on 2025-09-28 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0060_alter_forum_table'),
    ]

    operations = [
    ]
