# Generated by Django 5.2.3 on 2025-09-28 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0061_auto_20250929_0610'),
    ]

    operations = [
    ]
