# Generated by Django 5.2.3 on 2025-09-29 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0062_auto_20250929_0612'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='forum',
            table=None,
        ),
    ]
