# Generated by Django 5.2.3 on 2025-10-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0041_notification_is_read'),
        ('shared', '0063_alter_forum_table'),
    ]

    operations = [
    ]
