# Generated by Django 5.2.3 on 2025-10-01 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0064_merge_20251001_1827'),
    ]

    operations = [
        # Skip deleting ForumLike and ForumComment as they don't exist in database
        migrations.AddField(
            model_name='comment',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments', to='shared.forum'),
        ),
        migrations.AddField(
            model_name='like',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_likes', to='shared.forum'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='shared.post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='shared.post'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('forum__isnull', True), ('post__isnull', False)), models.Q(('forum__isnull', False), ('post__isnull', True)), _connector='OR'), name='comment_post_or_forum_not_both'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('forum__isnull', True), ('post__isnull', False)), models.Q(('forum__isnull', False), ('post__isnull', True)), _connector='OR'), name='like_post_or_forum_not_both'),
        ),
    ]
