# Generated by Django 5.2.3 on 2025-10-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0065_add_forum_support_to_interactions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forumlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='forumlike',
            name='forum',
        ),
        migrations.RemoveField(
            model_name='forumlike',
            name='user',
        ),
        migrations.DeleteModel(
            name='ForumComment',
        ),
        migrations.DeleteModel(
            name='ForumLike',
        ),
    ]
