# Generated by Django 5.2.3 on 2025-10-02 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0067_unify_repost_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_cat',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='post_cat',
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
