# Generated by Django 5.2.3 on 2025-10-02 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0075_delete_forumrepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='donation_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_comments', to='shared.donationrequest'),
        ),
        migrations.AddField(
            model_name='like',
            name='donation_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_likes', to='shared.donationrequest'),
        ),
        migrations.AddField(
            model_name='repost',
            name='donation_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_reposts', to='shared.donationrequest'),
        ),
    ]
