# Generated by Django 5.2.3 on 2025-10-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0076_add_donation_interactions'),
    ]

    operations = [
        # Only delete the models that actually exist
        migrations.DeleteModel(
            name='RepostComment',
        ),
        migrations.DeleteModel(
            name='RepostLike',
        ),
    ]
