# Generated by Django 5.2.3 on 2025-10-02 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0079_delete_forumrepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='repost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repost_likes', to='shared.repost'),
        ),
        migrations.AddField(
            model_name='comment',
            name='repost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repost_comments', to='shared.repost'),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
