# Generated by Django 5.2.3 on 2025-10-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0080_auto_20251003_0041'),
    ]

    operations = [
        # Drop the old constraint
        migrations.RunSQL(
            "ALTER TABLE shared_like DROP CONSTRAINT IF EXISTS like_post_or_forum_not_both;",
            reverse_sql="-- No reverse operation needed"
        ),
        # Drop the old constraint for comments too
        migrations.RunSQL(
            "ALTER TABLE shared_comment DROP CONSTRAINT IF EXISTS comment_post_or_forum_not_both;",
            reverse_sql="-- No reverse operation needed"
        ),
        # Add the new constraints
        migrations.RunSQL(
            """
            ALTER TABLE shared_like ADD CONSTRAINT like_one_content_type_only 
            CHECK (
                (post_id IS NOT NULL AND forum_id IS NULL AND donation_request_id IS NULL AND repost_id IS NULL) OR
                (post_id IS NULL AND forum_id IS NOT NULL AND donation_request_id IS NULL AND repost_id IS NULL) OR
                (post_id IS NULL AND forum_id IS NULL AND donation_request_id IS NOT NULL AND repost_id IS NULL) OR
                (post_id IS NULL AND forum_id IS NULL AND donation_request_id IS NULL AND repost_id IS NOT NULL)
            );
            """,
            reverse_sql="ALTER TABLE shared_like DROP CONSTRAINT IF EXISTS like_one_content_type_only;"
        ),
        migrations.RunSQL(
            """
            ALTER TABLE shared_comment ADD CONSTRAINT comment_one_content_type_only 
            CHECK (
                (post_id IS NOT NULL AND forum_id IS NULL AND donation_request_id IS NULL AND repost_id IS NULL) OR
                (post_id IS NULL AND forum_id IS NOT NULL AND donation_request_id IS NULL AND repost_id IS NULL) OR
                (post_id IS NULL AND forum_id IS NULL AND donation_request_id IS NOT NULL AND repost_id IS NULL) OR
                (post_id IS NULL AND forum_id IS NULL AND donation_request_id IS NULL AND repost_id IS NOT NULL)
            );
            """,
            reverse_sql="ALTER TABLE shared_comment DROP CONSTRAINT IF EXISTS comment_one_content_type_only;"
        ),
    ]
