# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0081_fix_like_constraint'),
    ]

    operations = [
        # Empty migration - no operations needed
    ]
