# Generated by Django 5.2.3 on 2025-10-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0087_remove_forum_post_id_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='file_type',
            field=models.CharField(max_length=255),
        ),
    ]
