# Generated by Django 5.2.3 on 2025-10-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0088_increase_file_type_length'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='academicinfo',
            name='shared_acad_year_gr_8d0e79_idx',
        ),
        migrations.RemoveField(
            model_name='academicinfo',
            name='course',
        ),
        migrations.AddIndex(
            model_name='academicinfo',
            index=models.Index(fields=['year_graduated', 'program'], name='shared_acad_year_gr_544607_idx'),
        ),
    ]
