# Generated by Django 5.1.7 on 2025-10-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_recentsearch'),
        ('shared', '0084_question_required'),
        ('shared', '0093_add_cross_program_alignment_fields'),
    ]

    operations = [
    ]
