# Generated by Django 5.2.3 on 2025-10-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0083_add_missing_repost_fields'),
        ('shared', '0084_question_required'),
        ('shared', '0093_add_cross_program_alignment_fields'),
    ]

    operations = [
    ]
