# Generated by Django 5.2.3 on 2025-10-14 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_add_cloud_storage_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OJTCompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='employmenthistory',
            name='shared_empl_absorbe_idx',
        ),
        migrations.RemoveIndex(
            model_name='ojtinfo',
            name='shared_ojti_ojt_sta_idx',
        ),
        migrations.RemoveIndex(
            model_name='trackerdata',
            name='shared_trac_q_secto_idx',
        ),
        migrations.RemoveIndex(
            model_name='trackerdata',
            name='shared_trac_q_scope_idx',
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='company_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ojtimport',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ojtinfo',
            name='is_sent_to_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ojtinfo',
            name='sent_to_admin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ojtcompanyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ojt_company_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recentsearch',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_searches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recentsearch',
            name='searched_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appears_in_recent_searches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ojtcompanyprofile',
            index=models.Index(fields=['company_name'], name='shared_ojtc_company_73494f_idx'),
        ),
        migrations.AddIndex(
            model_name='ojtcompanyprofile',
            index=models.Index(fields=['start_date'], name='shared_ojtc_start_d_a99721_idx'),
        ),
        migrations.AddIndex(
            model_name='ojtcompanyprofile',
            index=models.Index(fields=['end_date'], name='shared_ojtc_end_dat_3e437e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recentsearch',
            unique_together={('owner', 'searched_user')},
        ),
    ]
