# Generated by Django 5.1.7 on 2025-10-08 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0094_merge_20251008_2311'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employmenthistory',
            name='shared_empl_absorbe_idx',
        ),
        migrations.RemoveIndex(
            model_name='ojtinfo',
            name='shared_ojti_ojt_sta_idx',
        ),
        migrations.RemoveIndex(
            model_name='trackerdata',
            name='shared_trac_q_secto_idx',
        ),
        migrations.RemoveIndex(
            model_name='trackerdata',
            name='shared_trac_q_scope_idx',
        ),
    ]
