# Generated by Django 5.2.3 on 2025-10-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0095_ojtcompanyprofile_recentsearch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator', models.CharField(max_length=100)),
                ('batch_year', models.IntegerField()),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('send_date', models.DateField()),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('coordinator', 'batch_year', 'section')},
            },
        ),
    ]
