# Generated by Django 5.2.3 on 2025-10-11 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0083_add_missing_repost_fields'),
        ('shared', '0095_remove_employmenthistory_shared_empl_absorbe_idx_and_more'),
        ('shared', '0096_add_coordinator_program_model'),
    ]

    operations = [
    ]
