# Generated by Django 5.2.3 on 2025-10-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0096_senddate'),
    ]

    operations = [
    ]
