# Generated by Django 5.2.3 on 2025-10-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0103_merge_20251021_2330'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE shared_question "
                        "ADD COLUMN IF NOT EXISTS \"order\" integer DEFAULT 0;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE shared_question "
                        "DROP COLUMN IF EXISTS \"order\";"
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='question',
                    name='order',
                    field=models.PositiveIntegerField(default=0),
                ),
            ],
        ),
    ]
