# Generated by Django 5.2.3 on 2025-10-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0097_auto_20251018_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
