# Generated by Django 5.2.3 on 2025-10-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0095_ojtcompanyprofile_recentsearch_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE shared_employmenthistory "
                        "ADD COLUMN IF NOT EXISTS company_contact varchar(20);"
                    ),
                    reverse_sql=(
                        "ALTER TABLE shared_employmenthistory "
                        "DROP COLUMN IF EXISTS company_contact;"
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE shared_employmenthistory "
                        "ADD COLUMN IF NOT EXISTS company_email varchar(254);"
                    ),
                    reverse_sql=(
                        "ALTER TABLE shared_employmenthistory "
                        "DROP COLUMN IF EXISTS company_email;"
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE shared_employmenthistory "
                        "ADD COLUMN IF NOT EXISTS contact_person varchar(255);"
                    ),
                    reverse_sql=(
                        "ALTER TABLE shared_employmenthistory "
                        "DROP COLUMN IF EXISTS contact_person;"
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE shared_employmenthistory "
                        "ADD COLUMN IF NOT EXISTS position varchar(255);"
                    ),
                    reverse_sql=(
                        "ALTER TABLE shared_employmenthistory "
                        "DROP COLUMN IF EXISTS position;"
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='employmenthistory',
                    name='company_contact',
                    field=models.CharField(blank=True, max_length=20, null=True),
                ),
                migrations.AddField(
                    model_name='employmenthistory',
                    name='company_email',
                    field=models.EmailField(blank=True, max_length=254, null=True),
                ),
                migrations.AddField(
                    model_name='employmenthistory',
                    name='contact_person',
                    field=models.CharField(blank=True, max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name='employmenthistory',
                    name='position',
                    field=models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
