# Generated by Django 5.2.3 on 2025-10-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0098_add_missing_employment_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE shared_ojtimport "
                        "ADD COLUMN IF NOT EXISTS section varchar(50);"
                    ),
                    reverse_sql=(
                        "ALTER TABLE shared_ojtimport "
                        "DROP COLUMN IF EXISTS section;"
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='ojtimport',
                    name='section',
                    field=models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
    ]
