# Generated by Django 5.2.3 on 2025-10-12 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0098_add_missing_employment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojtimport',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
