# Generated by Django 5.2.3 on 2025-10-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0098_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_message_request',
            field=models.BooleanField(default=False, help_text='True if this is a message request from non-mutual follow'),
        ),
    ]
