# Generated by Django 5.2.3 on 2025-10-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0098_question_order'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE shared_conversation "
                        "ADD COLUMN IF NOT EXISTS is_message_request boolean DEFAULT FALSE;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE shared_conversation "
                        "DROP COLUMN IF EXISTS is_message_request;"
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='conversation',
                    name='is_message_request',
                    field=models.BooleanField(default=False, help_text='True if this is a message request from non-mutual follow'),
                ),
            ],
        ),
    ]
