# Generated by Django 5.2.3 on 2025-10-28 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0099_add_message_request_field'),
    ]

    operations = [
        # Migration already applied manually - column exists in database
        # migrations.AddField(
        #     model_name='conversation',
        #     name='request_initiator',
        #     field=models.ForeignKey(blank=True, help_text='User who initiated the message request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_message_requests', to=settings.AUTH_USER_MODEL),
        # ),
    ]
