# Generated by Django 5.2.3 on 2025-10-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0100_ojtinfo_is_sent_to_admin_ojtinfo_sent_to_admin_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('forum', 'Forum'), ('donation', 'Donation')], max_length=20)),
                ('content_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='content_images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shared_contentimage',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['content_type', 'content_id'], name='shared_cont_content_28a4ab_idx'), models.Index(fields=['content_type', 'content_id', 'order'], name='shared_cont_content_6866fc_idx')],
                'unique_together': {('content_type', 'content_id', 'order')},
            },
        ),
        migrations.DeleteModel(
            name='DonationImage',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
