# Generated by Django 5.2.3 on 2025-10-09 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0101_remove_postimage_post_remove_forum_image_and_more'),
    ]

    operations = [
    ]
