# Generated by Django 5.2.3 on 2025-10-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_add_cloud_storage_fields'),
        ('shared', '0096_senddate'),
        ('shared', '0102_remove_employmenthistory_shared_empl_absorbe_idx_and_more'),
    ]

    operations = [
    ]
