# Generated by Django 5.2.3 on 2025-10-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0103_merge_20251021_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
