# Generated by Django 5.2.3 on 2025-10-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0104_alter_reply_reply_content'),
        ('shared', '0105_create_shared_reply_if_missing'),
    ]

    operations = [
    ]
