# Generated by Django 5.2.3 on 2025-10-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0100_conversation_request_initiator'),
        ('shared', '0107_rewardhistory'),
    ]

    operations = [
    ]
