# Generated by Django 5.2.3 on 2025-10-28 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0108_merge_20251028_2004'),
    ]

    operations = [
        # Ensure Reply table exists before trying to alter it
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "CREATE TABLE IF NOT EXISTS shared_reply ("
                        "reply_id serial PRIMARY KEY,"
                        "reply_content text,"
                        "date_created timestamp with time zone NOT NULL DEFAULT now(),"
                        "comment_id integer NOT NULL REFERENCES shared_comment(comment_id) ON DELETE CASCADE,"
                        "user_id integer NOT NULL REFERENCES shared_user(user_id) ON DELETE CASCADE"
                        ");"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=(
                        "DO $$ BEGIN "
                        "IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'shared_repl_comment_657ed9_idx') THEN "
                        "CREATE INDEX shared_repl_comment_657ed9_idx ON shared_reply (comment_id, date_created); "
                        "END IF; END $$;"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=(
                        "DO $$ BEGIN "
                        "IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'shared_repl_user_id_240ea8_idx') THEN "
                        "CREATE INDEX shared_repl_user_id_240ea8_idx ON shared_reply (user_id, date_created); "
                        "END IF; END $$;"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                # No-op for state since Reply should already be in state from 0100
            ],
        ),
        migrations.RenameIndex(
            model_name='rewardhistory',
            new_name='shared_rewa_user_id_1d3ef5_idx',
            old_name='shared_rewardhistory_user_idx',
        ),
        migrations.RenameIndex(
            model_name='rewardhistory',
            new_name='shared_rewa_given_a_f51498_idx',
            old_name='shared_rewardhistory_given_idx',
        ),
        migrations.RenameIndex(
            model_name='rewardinventoryitem',
            new_name='shared_rewa_type_51f6c9_idx',
            old_name='shared_rewardinv_type_idx',
        ),
        migrations.RenameIndex(
            model_name='rewardinventoryitem',
            new_name='shared_rewa_created_42ad9b_idx',
            old_name='shared_rewardinv_created_idx',
        ),
        migrations.RenameIndex(
            model_name='userpoints',
            new_name='shared_user_total_p_4d1c1f_idx',
            old_name='shared_user_total_p_idx',
        ),
        migrations.RenameIndex(
            model_name='userpoints',
            new_name='shared_user_user_id_88bfc7_idx',
            old_name='shared_user_user_id_idx',
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_content',
            field=models.TextField(default='No Content'),
            preserve_default=False,
        ),
    ]
