# Generated by Django 5.2.3 on 2025-10-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0108_merge_20251028_2004'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rewardhistory',
            new_name='shared_rewa_user_id_1d3ef5_idx',
            old_name='shared_rewardhistory_user_idx',
        ),
        migrations.RenameIndex(
            model_name='rewardhistory',
            new_name='shared_rewa_given_a_f51498_idx',
            old_name='shared_rewardhistory_given_idx',
        ),
        migrations.RenameIndex(
            model_name='rewardinventoryitem',
            new_name='shared_rewa_type_51f6c9_idx',
            old_name='shared_rewardinv_type_idx',
        ),
        migrations.RenameIndex(
            model_name='rewardinventoryitem',
            new_name='shared_rewa_created_42ad9b_idx',
            old_name='shared_rewardinv_created_idx',
        ),
        migrations.RenameIndex(
            model_name='userpoints',
            new_name='shared_user_total_p_4d1c1f_idx',
            old_name='shared_user_total_p_idx',
        ),
        migrations.RenameIndex(
            model_name='userpoints',
            new_name='shared_user_user_id_88bfc7_idx',
            old_name='shared_user_user_id_idx',
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_content',
            field=models.TextField(default='No Content'),
            preserve_default=False,
        ),
    ]
