# Generated by Django 5.2.3 on 2025-10-30 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0109_rename_shared_rewardhistory_user_idx_shared_rewa_user_id_1d3ef5_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSettings',
            fields=[
                ('settings_id', models.AutoField(primary_key=True, serialize=False)),
                ('header_enabled', models.BooleanField(default=True, help_text='Enable/disable header')),
                ('header_layout_type', models.CharField(choices=[('three_column', 'Three Column (Logo, Text, Logo)'), ('two_column', 'Two Column (Logo, Text)'), ('single_column', 'Single Column (Text only)')], default='three_column', help_text='Header layout type', max_length=20)),
                ('left_logo_enabled', models.BooleanField(default=True, help_text='Show left logo')),
                ('left_logo', models.ImageField(blank=True, null=True, upload_to='report_logos/')),
                ('right_logo_enabled', models.BooleanField(default=True, help_text='Show right logo')),
                ('right_logo', models.ImageField(blank=True, null=True, upload_to='report_logos/')),
                ('header_line1', models.CharField(default='Republic of the Philippines', help_text='Header line 1', max_length=255)),
                ('header_line2', models.CharField(default='CEBU TECHNOLOGICAL UNIVERSITY', help_text='Header line 2', max_length=255)),
                ('header_line2_color', models.CharField(default='#DC143C', help_text='Header line 2 color (hex)', max_length=7)),
                ('header_line2_bold', models.BooleanField(default=True)),
                ('header_line3', models.CharField(default='M. J. Cuenco Avenue Cor. R. Palma Street, Cebu City, Philippines', help_text='Header line 3', max_length=255)),
                ('header_line4', models.CharField(default='Website: http://www.ctu.edu.ph', help_text='Header line 4', max_length=255)),
                ('header_line5', models.CharField(default='Phone: +6332 402 4060 loc. 1146', help_text='Header line 5', max_length=255)),
                ('header_line6', models.CharField(default='UNIVERSITY ALUMNI AFFAIRS OFFICE', help_text='Header line 6', max_length=255)),
                ('header_line6_color', models.CharField(default='#DC143C', help_text='Header line 6 color (hex)', max_length=7)),
                ('header_line6_bold', models.BooleanField(default=True)),
                ('footer_enabled', models.BooleanField(default=True, help_text='Enable/disable footer')),
                ('footer_image_enabled', models.BooleanField(default=True, help_text='Show footer image')),
                ('footer_image', models.ImageField(blank=True, null=True, upload_to='report_logos/')),
                ('footer_text1', models.CharField(default='Generated by Cebu Technological University Alumni Affairs Office', help_text='Footer text 1', max_length=255)),
                ('footer_text2', models.CharField(default='This report is generated automatically by the Alumni Tracking System', help_text='Footer text 2', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_settings', models.JSONField(blank=True, default=dict, help_text='Additional custom settings')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_settings_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Settings',
                'verbose_name_plural': 'Report Settings',
                'db_table': 'shared_reportsettings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
