# Generated by Django 5.2.3 on 2025-10-30 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0110_add_report_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsettings',
            name='approved_by_name',
            field=models.CharField(default='ROMEO P. MONTECILLO, Ph.D.', help_text='Approved by name', max_length=255),
        ),
        migrations.AddField(
            model_name='reportsettings',
            name='approved_by_title',
            field=models.CharField(default='Vice President for Student Affairs', help_text='Approved by title', max_length=255),
        ),
        migrations.AddField(
            model_name='reportsettings',
            name='prepared_by_name',
            field=models.CharField(default='MARIE JOY B. ALIT, Ph.D.', help_text='Prepared by name', max_length=255),
        ),
        migrations.AddField(
            model_name='reportsettings',
            name='prepared_by_title',
            field=models.CharField(default='University Director for Alumni Affairs', help_text='Prepared by title', max_length=255),
        ),
        migrations.AddField(
            model_name='reportsettings',
            name='signature_enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable signature section'),
        ),
    ]
