# Generated by Django 5.2.3 on 2025-11-07 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0112_conversation_request_initiator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportsettings',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Header/Footer Settings', 'verbose_name_plural': 'Header/Footer Settings'},
        ),
    ]
