# Generated by Django 5.2.3 on 2025-11-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0113_rewardrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementPointsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Enable or disable the points system')),
                ('like_points', models.IntegerField(default=1, help_text='Points for liking a post')),
                ('comment_points', models.IntegerField(default=3, help_text='Points for commenting on a post')),
                ('share_points', models.IntegerField(default=5, help_text='Points for sharing/reposting a post')),
                ('reply_points', models.IntegerField(default=2, help_text='Points for replying to a comment')),
                ('post_with_photo_points', models.IntegerField(default=15, help_text='Points for posting with photos')),
                ('tracker_form_points', models.IntegerField(default=0, help_text='Points for completing tracker form')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Engagement Points Settings',
                'verbose_name_plural': 'Engagement Points Settings',
                'db_table': 'shared_engagementpointssettings',
            },
        ),
        migrations.RenameIndex(
            model_name='rewardrequest',
            new_name='shared_rewa_user_id_e7cd69_idx',
            old_name='shared_rewa_user_idx',
        ),
        migrations.RenameIndex(
            model_name='rewardrequest',
            new_name='shared_rewa_status_6e0f91_idx',
            old_name='shared_rewa_status_idx',
        ),
        migrations.RenameIndex(
            model_name='rewardrequest',
            new_name='shared_rewa_request_f07926_idx',
            old_name='shared_rewa_request_idx',
        ),
        migrations.RenameIndex(
            model_name='rewardrequest',
            new_name='shared_rewa_expires_66cb2e_idx',
            old_name='shared_rewa_expires_idx',
        ),
    ]
