# Generated by Django 5.2.3 on 2025-11-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0113_alter_reportsettings_options'),
        ('shared', '0115_add_missing_points_fields'),
    ]

    operations = [
    ]
