# Generated by Django 5.2.3 on 2025-11-09 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0115_add_missing_points_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementpointssettings',
            name='daily_comment_limit',
            field=models.IntegerField(default=50, help_text='Maximum comments per day'),
        ),
        migrations.AddField(
            model_name='engagementpointssettings',
            name='daily_like_limit',
            field=models.IntegerField(default=100, help_text='Maximum likes per day'),
        ),
        migrations.AddField(
            model_name='engagementpointssettings',
            name='daily_post_limit',
            field=models.IntegerField(default=10, help_text='Maximum posts per day'),
        ),
        migrations.AddField(
            model_name='engagementpointssettings',
            name='daily_post_with_photo_limit',
            field=models.IntegerField(default=10, help_text='Maximum posts with photos per day'),
        ),
        migrations.AddField(
            model_name='engagementpointssettings',
            name='daily_reply_limit',
            field=models.IntegerField(default=50, help_text='Maximum replies per day'),
        ),
        migrations.AddField(
            model_name='engagementpointssettings',
            name='daily_share_limit',
            field=models.IntegerField(default=20, help_text='Maximum shares/reposts per day'),
        ),
        migrations.AddField(
            model_name='engagementpointssettings',
            name='daily_tracker_form_limit',
            field=models.IntegerField(default=1, help_text='Maximum tracker form submissions per day'),
        ),
        migrations.AddField(
            model_name='engagementpointssettings',
            name='hourly_comment_limit',
            field=models.IntegerField(default=10, help_text='Maximum comments per hour'),
        ),
        migrations.AddField(
            model_name='engagementpointssettings',
            name='hourly_like_limit',
            field=models.IntegerField(default=20, help_text='Maximum likes per hour'),
        ),
        migrations.AddField(
            model_name='engagementpointssettings',
            name='hourly_post_limit',
            field=models.IntegerField(default=2, help_text='Maximum posts per hour'),
        ),
        migrations.AddField(
            model_name='engagementpointssettings',
            name='hourly_post_with_photo_limit',
            field=models.IntegerField(default=2, help_text='Maximum posts with photos per hour'),
        ),
        migrations.AddField(
            model_name='engagementpointssettings',
            name='hourly_reply_limit',
            field=models.IntegerField(default=10, help_text='Maximum replies per hour'),
        ),
        migrations.AddField(
            model_name='engagementpointssettings',
            name='hourly_share_limit',
            field=models.IntegerField(default=5, help_text='Maximum shares/reposts per hour'),
        ),
        migrations.AddField(
            model_name='engagementpointssettings',
            name='hourly_tracker_form_limit',
            field=models.IntegerField(default=1, help_text='Maximum tracker form submissions per hour'),
        ),
        migrations.AddField(
            model_name='engagementpointssettings',
            name='rate_limiting_enabled',
            field=models.BooleanField(default=True, help_text='Enable rate limiting to prevent spam'),
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(help_text='Type of action: like, comment, share, reply, post, post_with_photo, tracker_form', max_length=50)),
                ('action_timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Action Log',
                'verbose_name_plural': 'User Action Logs',
                'db_table': 'shared_useractionlog',
                'ordering': ['-action_timestamp'],
                'indexes': [models.Index(fields=['user', 'action_type', '-action_timestamp'], name='shared_user_user_id_738f0a_idx'), models.Index(fields=['user', '-action_timestamp'], name='shared_user_user_id_8a8342_idx'), models.Index(fields=['action_timestamp'], name='shared_user_action__f4a71a_idx')],
            },
        ),
    ]
