# Generated by Django 5.2.3 on 2025-11-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0116_merge_20251107_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerresponse',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackerresponse',
            name='last_saved_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
