# Generated by Django 5.1.7 on 2025-11-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0116_merge_20251108_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementpointssettings',
            name='comment_points',
            field=models.IntegerField(default=2, help_text='Points for commenting on a post'),
        ),
        migrations.AlterField(
            model_name='engagementpointssettings',
            name='post_points',
            field=models.IntegerField(default=5, help_text='Points for posting without photos'),
        ),
        migrations.AlterField(
            model_name='engagementpointssettings',
            name='post_with_photo_points',
            field=models.IntegerField(default=10, help_text='Points for posting with photos'),
        ),
        migrations.AlterField(
            model_name='engagementpointssettings',
            name='reply_points',
            field=models.IntegerField(default=3, help_text='Points for replying to a comment'),
        ),
        migrations.AlterField(
            model_name='engagementpointssettings',
            name='share_points',
            field=models.IntegerField(default=3, help_text='Points for sharing/reposting a post'),
        ),
        migrations.AlterField(
            model_name='engagementpointssettings',
            name='tracker_form_points',
            field=models.IntegerField(default=10, help_text='Points for completing tracker form'),
        ),
    ]
