# Generated by Django 5.2.3 on 2025-11-10 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0116_add_rate_limiting'),
        ('shared', '0116_merge_20251108_1519'),
    ]

    operations = [
    ]
