# Generated by Django 5.2.3 on 2025-11-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0116_merge_20251107_1738'),
        ('shared', '0117_merge_0116_add_rate_limiting_0116_merge_20251108_1519'),
    ]

    operations = [
    ]
