# Generated by Django 5.2.3 on 2025-11-10 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0117_add_draft_fields_to_tracker_response'),
        ('shared', '0117_alter_engagementpointssettings_comment_points_and_more'),
        ('shared', '0117_merge_0116_add_rate_limiting_0116_merge_20251108_1519'),
    ]

    operations = [
    ]
