# Generated by Django 5.1.7 on 2025-11-10 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0118_merge_20251110_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='request_initiator',
            field=models.ForeignKey(blank=True, help_text='User who initiated the message request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_message_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='content_type',
            field=models.CharField(choices=[('post', 'Post'), ('forum', 'Forum'), ('donation', 'Donation'), ('comment', 'Comment'), ('reply', 'Reply')], max_length=20),
        ),
    ]
