# Generated by Django 5.2.3 on 2025-11-10 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0117_add_draft_fields_to_tracker_response'),
        ('shared', '0118_merge_20251110_1818'),
    ]

    operations = [
    ]
