# Generated by Django 5.2.3 on 2025-11-11 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models, connection


def check_and_add_userprofile_fields(apps, schema_editor):
    """Check if email_verified and preferences_completed columns exist before adding them"""
    with connection.cursor() as cursor:
        # Check for email_verified
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='shared_userprofile' 
            AND column_name='email_verified'
        """)
        email_verified_exists = cursor.fetchone()
        
        if not email_verified_exists:
            cursor.execute("""
                ALTER TABLE shared_userprofile 
                ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT FALSE
            """)
        
        # Check for preferences_completed
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='shared_userprofile' 
            AND column_name='preferences_completed'
        """)
        preferences_completed_exists = cursor.fetchone()
        
        if not preferences_completed_exists:
            cursor.execute("""
                ALTER TABLE shared_userprofile 
                ADD COLUMN preferences_completed BOOLEAN NOT NULL DEFAULT FALSE
            """)


def reverse_userprofile_fields(apps, schema_editor):
    """Remove the fields if they exist"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='shared_userprofile' 
            AND column_name='email_verified'
        """)
        if cursor.fetchone():
            cursor.execute("""
                ALTER TABLE shared_userprofile 
                DROP COLUMN IF EXISTS email_verified
            """)
        
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='shared_userprofile' 
            AND column_name='preferences_completed'
        """)
        if cursor.fetchone():
            cursor.execute("""
                ALTER TABLE shared_userprofile 
                DROP COLUMN IF EXISTS preferences_completed
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsTask',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('verify_email', 'Verify Email'), ('complete_preferences', 'Complete Preferences'), ('review_order', 'Review Order'), ('custom', 'Custom Task')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('points', models.IntegerField(help_text='Points awarded for completing this task')),
                ('max_points', models.IntegerField(blank=True, help_text='Maximum points (for variable point tasks like "up to X points")', null=True)),
                ('icon_name', models.CharField(default='envelope', help_text='Icon identifier for frontend', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Points Task',
                'verbose_name_plural': 'Points Tasks',
                'db_table': 'shared_pointstask',
                'ordering': ['order', 'task_id'],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(check_and_add_userprofile_fields, reverse_userprofile_fields),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='userprofile',
                    name='email_verified',
                    field=models.BooleanField(default=False, help_text='Whether the user has verified their email address'),
                ),
                migrations.AddField(
                    model_name='userprofile',
                    name='preferences_completed',
                    field=models.BooleanField(default=False, help_text='Whether the user has completed their preferences'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='engagementpointssettings',
            name='comment_points',
            field=models.IntegerField(default=2, help_text='Points for commenting on a post'),
        ),
        migrations.AlterField(
            model_name='engagementpointssettings',
            name='post_points',
            field=models.IntegerField(default=5, help_text='Points for posting without photos'),
        ),
        migrations.AlterField(
            model_name='engagementpointssettings',
            name='post_with_photo_points',
            field=models.IntegerField(default=10, help_text='Points for posting with photos'),
        ),
        migrations.AlterField(
            model_name='engagementpointssettings',
            name='reply_points',
            field=models.IntegerField(default=3, help_text='Points for replying to a comment'),
        ),
        migrations.AlterField(
            model_name='engagementpointssettings',
            name='share_points',
            field=models.IntegerField(default=3, help_text='Points for sharing/reposting a post'),
        ),
        migrations.AlterField(
            model_name='engagementpointssettings',
            name='tracker_form_points',
            field=models.IntegerField(default=10, help_text='Points for completing tracker form'),
        ),
        migrations.CreateModel(
            name='UserTaskCompletion',
            fields=[
                ('completion_id', models.AutoField(primary_key=True, serialize=False)),
                ('points_awarded', models.IntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='shared.pointstask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Task Completion',
                'verbose_name_plural': 'User Task Completions',
                'db_table': 'shared_usertaskcompletion',
                'indexes': [models.Index(fields=['user'], name='shared_user_user_id_6e7359_idx'), models.Index(fields=['task'], name='shared_user_task_id_4452a2_idx'), models.Index(fields=['-completed_at'], name='shared_user_complet_15bed3_idx')],
                'unique_together': {('user', 'task')},
            },
        ),
    ]
