# Generated by Django 5.2.3 on 2025-11-11 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models, connection


def check_and_add_request_initiator(apps, schema_editor):
    """Check if request_initiator_id column exists before adding it"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='shared_conversation' 
            AND column_name='request_initiator_id'
        """)
        exists = cursor.fetchone()
        
        if not exists:
            # Column doesn't exist, add it
            cursor.execute("""
                ALTER TABLE shared_conversation 
                ADD COLUMN request_initiator_id INTEGER NULL 
                REFERENCES shared_user(user_id) ON DELETE SET NULL
            """)
            # Add index for better performance
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS shared_conversation_request_initiator_id_idx 
                ON shared_conversation(request_initiator_id)
            """)


def reverse_request_initiator(apps, schema_editor):
    """Remove the field if it exists"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='shared_conversation' 
            AND column_name='request_initiator_id'
        """)
        exists = cursor.fetchone()
        
        if exists:
            cursor.execute("""
                DROP INDEX IF EXISTS shared_conversation_request_initiator_id_idx
            """)
            cursor.execute("""
                ALTER TABLE shared_conversation 
                DROP COLUMN IF EXISTS request_initiator_id
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0119_pointstask_conversation_request_initiator_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(check_and_add_request_initiator, reverse_request_initiator),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='conversation',
                    name='request_initiator',
                    field=models.ForeignKey(blank=True, help_text='User who initiated the message request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_message_requests', to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.AddField(
            model_name='userpoints',
            name='follow_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpoints',
            name='milestone_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpoints',
            name='points_from_milestones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pointstask',
            name='task_type',
            field=models.CharField(help_text='Unique identifier for the task (e.g., verify_email, milestone_post_10)', max_length=50, unique=True),
        ),
    ]
