# Generated by Django 5.2.3 on 2025-11-10 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0119_merge_20251110_1943'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1 FROM information_schema.columns
                            WHERE table_name = 'shared_conversation'
                              AND column_name = 'request_initiator_id'
                        ) THEN
                            ALTER TABLE shared_conversation
                            ADD COLUMN request_initiator_id INTEGER NULL
                                REFERENCES shared_user(user_id) ON DELETE SET NULL;
                        END IF;
                        CREATE INDEX IF NOT EXISTS shared_conversation_request_initiator_id_idx
                            ON shared_conversation(request_initiator_id);
                    END;
                    $$;
                    """,
                    reverse_sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1 FROM information_schema.columns
                            WHERE table_name = 'shared_conversation'
                              AND column_name = 'request_initiator_id'
                        ) THEN
                            DROP INDEX IF EXISTS shared_conversation_request_initiator_id_idx;
                            ALTER TABLE shared_conversation
                            DROP COLUMN request_initiator_id;
                        END IF;
                    END;
                    $$;
                    """
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='conversation',
                    name='request_initiator',
                    field=models.ForeignKey(
                        blank=True,
                        help_text='User who initiated the message request',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='initiated_message_requests',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='engagementpointssettings',
            name='comment_points',
            field=models.IntegerField(default=2, help_text='Points for commenting on a post'),
        ),
        migrations.AlterField(
            model_name='engagementpointssettings',
            name='post_points',
            field=models.IntegerField(default=5, help_text='Points for posting without photos'),
        ),
        migrations.AlterField(
            model_name='engagementpointssettings',
            name='post_with_photo_points',
            field=models.IntegerField(default=10, help_text='Points for posting with photos'),
        ),
        migrations.AlterField(
            model_name='engagementpointssettings',
            name='reply_points',
            field=models.IntegerField(default=3, help_text='Points for replying to a comment'),
        ),
        migrations.AlterField(
            model_name='engagementpointssettings',
            name='share_points',
            field=models.IntegerField(default=3, help_text='Points for sharing/reposting a post'),
        ),
        migrations.AlterField(
            model_name='engagementpointssettings',
            name='tracker_form_points',
            field=models.IntegerField(default=10, help_text='Points for completing tracker form'),
        ),
    ]
