# Generated by Django 5.2.3 on 2025-11-11 14:55

from django.db import migrations, models


def disable_rate_limiting(apps, schema_editor):
    Settings = apps.get_model('shared', 'EngagementPointsSettings')
    for settings in Settings.objects.all():
        settings.rate_limiting_enabled = False
        settings.daily_like_limit = 0
        settings.daily_comment_limit = 0
        settings.daily_share_limit = 0
        settings.daily_reply_limit = 0
        settings.daily_post_limit = 0
        settings.daily_post_with_photo_limit = 0
        settings.daily_tracker_form_limit = 0
        settings.hourly_like_limit = 0
        settings.hourly_comment_limit = 0
        settings.hourly_share_limit = 0
        settings.hourly_reply_limit = 0
        settings.hourly_post_limit = 0
        settings.hourly_post_with_photo_limit = 0
        settings.hourly_tracker_form_limit = 0
        settings.save(
            update_fields=[
                'rate_limiting_enabled',
                'daily_like_limit',
                'daily_comment_limit',
                'daily_share_limit',
                'daily_reply_limit',
                'daily_post_limit',
                'daily_post_with_photo_limit',
                'daily_tracker_form_limit',
                'hourly_like_limit',
                'hourly_comment_limit',
                'hourly_share_limit',
                'hourly_reply_limit',
                'hourly_post_limit',
                'hourly_post_with_photo_limit',
                'hourly_tracker_form_limit',
            ]
        )


def restore_rate_limiting_defaults(apps, schema_editor):
    Settings = apps.get_model('shared', 'EngagementPointsSettings')
    for settings in Settings.objects.all():
        settings.rate_limiting_enabled = True
        settings.daily_like_limit = 100
        settings.daily_comment_limit = 50
        settings.daily_share_limit = 20
        settings.daily_reply_limit = 50
        settings.daily_post_limit = 10
        settings.daily_post_with_photo_limit = 10
        settings.daily_tracker_form_limit = 1
        settings.hourly_like_limit = 20
        settings.hourly_comment_limit = 10
        settings.hourly_share_limit = 5
        settings.hourly_reply_limit = 10
        settings.hourly_post_limit = 2
        settings.hourly_post_with_photo_limit = 2
        settings.hourly_tracker_form_limit = 1
        settings.save(
            update_fields=[
                'rate_limiting_enabled',
                'daily_like_limit',
                'daily_comment_limit',
                'daily_share_limit',
                'daily_reply_limit',
                'daily_post_limit',
                'daily_post_with_photo_limit',
                'daily_tracker_form_limit',
                'hourly_like_limit',
                'hourly_comment_limit',
                'hourly_share_limit',
                'hourly_reply_limit',
                'hourly_post_limit',
                'hourly_post_with_photo_limit',
                'hourly_tracker_form_limit',
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0120_conversation_request_initiator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementpointssettings',
            name='rate_limiting_enabled',
            field=models.BooleanField(default=False, help_text='Enable rate limiting to prevent spam'),
        ),
        migrations.RunPython(disable_rate_limiting, restore_rate_limiting_defaults),
    ]
