# Generated by Django 5.2.3 on 2025-11-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0119_add_comment_reply_content_types'),
        ('shared', '0120_conversation_request_initiator_and_more'),
    ]

    operations = [
    ]
