# Generated by Django 5.2.3 on 2025-11-14 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0009_trackerfileupload'),
        ('shared', '0121_merge_20251113_1438'),
    ]

    operations = [
    ]
