# Generated by Django 5.2.3 on 2025-11-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0121_alter_engagementpointssettings_rate_limiting_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagementpointssettings',
            name='daily_comment_limit',
        ),
        migrations.RemoveField(
            model_name='engagementpointssettings',
            name='daily_like_limit',
        ),
        migrations.RemoveField(
            model_name='engagementpointssettings',
            name='daily_post_limit',
        ),
        migrations.RemoveField(
            model_name='engagementpointssettings',
            name='daily_post_with_photo_limit',
        ),
        migrations.RemoveField(
            model_name='engagementpointssettings',
            name='daily_reply_limit',
        ),
        migrations.RemoveField(
            model_name='engagementpointssettings',
            name='daily_share_limit',
        ),
        migrations.RemoveField(
            model_name='engagementpointssettings',
            name='daily_tracker_form_limit',
        ),
        migrations.RemoveField(
            model_name='engagementpointssettings',
            name='hourly_comment_limit',
        ),
        migrations.RemoveField(
            model_name='engagementpointssettings',
            name='hourly_like_limit',
        ),
        migrations.RemoveField(
            model_name='engagementpointssettings',
            name='hourly_post_limit',
        ),
        migrations.RemoveField(
            model_name='engagementpointssettings',
            name='hourly_post_with_photo_limit',
        ),
        migrations.RemoveField(
            model_name='engagementpointssettings',
            name='hourly_reply_limit',
        ),
        migrations.RemoveField(
            model_name='engagementpointssettings',
            name='hourly_share_limit',
        ),
        migrations.RemoveField(
            model_name='engagementpointssettings',
            name='hourly_tracker_form_limit',
        ),
        migrations.RemoveField(
            model_name='engagementpointssettings',
            name='rate_limiting_enabled',
        ),
        migrations.DeleteModel(
            name='UserActionLog',
        ),
    ]
