# Generated by Django 5.2.3 on 2025-11-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0124_pointstask_required_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojtcompanyprofile',
            name='coordinator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='ojtcompanyprofile',
            index=models.Index(fields=['coordinator'], name='shared_ojtc_coordin_b06a95_idx'),
        ),
    ]
