# Generated by Django 5.2.3 on 2025-11-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0126_add_tracker_form_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojtinfo',
            name='address',
            field=models.TextField(blank=True, help_text='Student address', null=True),
        ),
        migrations.AddField(
            model_name='ojtinfo',
            name='email',
            field=models.EmailField(blank=True, help_text='Student email address for OJT purposes', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ojtinfo',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or remarks about the OJT', null=True),
        ),
        migrations.AddField(
            model_name='ojtinfo',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Student contact number', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='ojtinfo',
            index=models.Index(fields=['email'], name='shared_ojti_email_5c6bf2_idx'),
        ),
    ]
