# Generated by Django 5.2.3 on 2025-11-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0126_add_tracker_form_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobeAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('access_token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Globe Access Token',
                'verbose_name_plural': 'Globe Access Tokens',
                'db_table': 'globe_access_tokens',
            },
        ),
    ]
