# Generated by Django 5.2.3 on 2025-11-16 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0128_make_ojt_email_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ojtinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ojtinfo',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='ojtinfo',
            name='phone_number',
        ),
    ]
