# Generated by Django 5.2.3 on 2025-11-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0128_passwordresettoken'),
    ]

    operations = [
        # Add index on updated_at for conversation list sorting performance
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-updated_at'], name='conversation_updated_at_idx'),
        ),
        # Add composite index for participant filtering with ordering
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['created_at'], name='conversation_created_at_idx'),
        ),
    ]
