# Generated by Django 5.2.3 on 2025-11-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0129_add_conversation_updated_at_index'),
        ('shared', '0130_backfill_trackerresponse_draft_columns'),
    ]

    operations = [
    ]
