# Generated by Django 5.2.3 on 2025-11-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0131_merge_20251118_1843'),
    ]

    operations = [
        # Use RunSQL to safely remove index and field if they exist
        # This makes the migration safe to run even if the column was already removed
        migrations.RunSQL(
            sql=[
                # Remove index if it exists (PostgreSQL/MySQL compatible)
                "DROP INDEX IF EXISTS shared_ojti_email_5c6bf2_idx;",
                # For PostgreSQL, also try this format
                "ALTER TABLE shared_ojtinfo DROP CONSTRAINT IF EXISTS shared_ojti_email_5c6bf2_idx;",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE shared_ojtinfo DROP COLUMN IF EXISTS email;",
            reverse_sql="ALTER TABLE shared_ojtinfo ADD COLUMN IF NOT EXISTS email varchar(254);",
        ),
    ]
