# Generated by Django 5.2.3 on 2025-11-21 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0131_move_ojt_email_to_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('add', 'Add Stock'), ('deduct', 'Deduct Stock'), ('reserve', 'Reserve Stock'), ('release', 'Release Reservation'), ('adjust', 'Manual Adjustment')], default='adjust', max_length=20)),
                ('quantity_change', models.IntegerField(default=0)),
                ('reserved_change', models.IntegerField(default=0)),
                ('previous_quantity', models.IntegerField(default=0)),
                ('new_quantity', models.IntegerField(default=0)),
                ('previous_reserved_quantity', models.IntegerField(default=0)),
                ('new_reserved_quantity', models.IntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shared_inventorytransaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardItemBatch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=100)),
                ('quantity_in_batch', models.IntegerField(default=0)),
                ('quantity_available', models.IntegerField(default=0)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('supplier_info', models.CharField(blank=True, max_length=255, null=True)),
                ('fulfillment_strategy', models.CharField(choices=[('fifo', 'First In, First Out'), ('lifo', 'Last In, First Out')], default='fifo', help_text='Determines which batches are consumed first', max_length=10)),
                ('received_at', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shared_rewarditembatch',
                'ordering': ['expiry_date', 'received_at'],
            },
        ),
        migrations.AddField(
            model_name='rewardinventoryitem',
            name='category',
            field=models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical'), ('points', 'Points'), ('other', 'Other')], default='other', help_text='High-level grouping for display/handling rules', max_length=50),
        ),
        migrations.AddField(
            model_name='rewardinventoryitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If false, hide from request listings even if stock exists'),
        ),
        migrations.AddField(
            model_name='rewardinventoryitem',
            name='low_stock_threshold',
            field=models.IntegerField(default=5, help_text='Trigger level for low-stock alerts'),
        ),
        migrations.AddField(
            model_name='rewardinventoryitem',
            name='reorder_point',
            field=models.IntegerField(default=0, help_text='Optional level where procurement should reorder'),
        ),
        migrations.AddField(
            model_name='rewardinventoryitem',
            name='reserved_quantity',
            field=models.IntegerField(default=0, help_text='Units currently reserved for pending/approved requests'),
        ),
        migrations.AddField(
            model_name='rewardrequest',
            name='reserved_until',
            field=models.DateTimeField(blank=True, help_text='Reservation expiry timestamp', null=True),
        ),
        migrations.AddIndex(
            model_name='rewardinventoryitem',
            index=models.Index(fields=['category'], name='shared_rewa_categor_9aa0ba_idx'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='shared.rewardinventoryitem'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewarditembatch',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='shared.rewardinventoryitem'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['item'], name='shared_inve_item_id_44638f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['transaction_type'], name='shared_inve_transac_1f447b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['-created_at'], name='shared_inve_created_222575_idx'),
        ),
        migrations.AddIndex(
            model_name='rewarditembatch',
            index=models.Index(fields=['item'], name='shared_rewa_item_id_6b1930_idx'),
        ),
        migrations.AddIndex(
            model_name='rewarditembatch',
            index=models.Index(fields=['expiry_date'], name='shared_rewa_expiry__e1de71_idx'),
        ),
    ]
