# Generated by Django 5.2.3 on 2025-11-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0131_merge_20251118_1758'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='conversation_updated_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='conversation_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='ojtinfo',
            name='shared_ojti_email_5c6bf2_idx',
        ),
        migrations.RemoveField(
            model_name='ojtinfo',
            name='email',
        ),
    ]
