# Generated by Django 5.2.3 on 2025-11-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0131_merge_20251118_1843'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ojtinfo',
            name='shared_ojti_email_5c6bf2_idx',
        ),
        migrations.RemoveField(
            model_name='ojtinfo',
            name='email',
        ),
    ]
