# Generated by Django 5.2.3 on 2025-11-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0131_merge_20251118_2226'),
        ('shared', '0132_remove_ojtinfo_shared_ojti_email_5c6bf2_idx_and_more'),
    ]

    operations = [
    ]
