# Generated by Django 5.2.3 on 2025-11-21 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0132_remove_ojtinfo_shared_ojti_email_5c6bf2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('reaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('emoji', models.CharField(help_text='Unicode emoji character (e.g., 😊, ❤️, 👍)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(help_text='The message being reacted to', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='shared.message')),
                ('user', models.ForeignKey(help_text='The user who reacted', on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message_reactions',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['message', 'created_at'], name='message_rea_message_868f44_idx'), models.Index(fields=['user'], name='message_rea_user_id_565363_idx')],
                'unique_together': {('message', 'user', 'emoji')},
            },
        ),
    ]
