# Generated by Django 5.2.3 on 2025-11-21 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0133_messagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False, help_text='Whether the message has been edited'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, help_text='The message this is replying to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='shared.message'),
        ),
    ]
