# Generated by Django 5.2.3 on 2025-11-18 14:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0133_merge_20251118_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojtinfo',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, help_text='Student email address for OJT purposes (required)', max_length=254),
            preserve_default=False,
        ),
        # Note: Conversation indexes are already defined in the model Meta class
        # and should already exist from migration 0129. If they were removed by 0132,
        # they will be recreated automatically by Django when makemigrations detects
        # the mismatch between model definition and database state.
    ]
