# Generated by Django 5.2.3 on 2025-11-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0133_remove_ojtinfo_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='rewarditembatch',
            name='item',
        ),
        migrations.RemoveIndex(
            model_name='rewardinventoryitem',
            name='shared_rewa_categor_9aa0ba_idx',
        ),
        migrations.RemoveField(
            model_name='rewardinventoryitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='rewardinventoryitem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='rewardinventoryitem',
            name='low_stock_threshold',
        ),
        migrations.RemoveField(
            model_name='rewardinventoryitem',
            name='reorder_point',
        ),
        migrations.RemoveField(
            model_name='rewardinventoryitem',
            name='reserved_quantity',
        ),
        migrations.RemoveField(
            model_name='rewardrequest',
            name='reserved_until',
        ),
        migrations.AlterField(
            model_name='rewardrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('ready_for_pickup', 'Ready for Pickup'), ('claimed', 'Claimed'), ('expired', 'Expired'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='InventoryTransaction',
        ),
        migrations.DeleteModel(
            name='RewardItemBatch',
        ),
    ]
