# Generated by Django 5.2.3 on 2025-11-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0134_add_cancelled_status_to_reward_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardrequest',
            name='cancellation_stage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rewardrequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
