# Generated by Django 5.2.3 on 2025-11-21 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0134_message_is_edited_message_reply_to'),
        ('shared', '0135_add_cooldown_fields_to_reward_request'),
    ]

    operations = [
    ]
