# Generated by Django 5.1.7 on 2025-11-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0134_ojtinfo_email_and_more'),
        ('shared', '0136_merge_20251121_2020'),
    ]

    operations = [
    ]
