# Generated by Django 5.2.3 on 2025-11-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0137_merge_20251121_2347'),
    ]

    operations = [
        # Use RunSQL to safely remove the email column if it exists
        # This handles the case where the column may have already been removed
        migrations.RunSQL(
            sql="ALTER TABLE shared_ojtinfo DROP COLUMN IF EXISTS email;",
            reverse_sql="ALTER TABLE shared_ojtinfo ADD COLUMN IF NOT EXISTS email varchar(254);",
            state_operations=[
                migrations.RemoveField(
                    model_name='ojtinfo',
                    name='email',
                ),
            ],
        ),
    ]
