# Generated by Django 5.2.3 on 2025-11-24 07:07
# Fixed: Use RunSQL with IF EXISTS to safely handle case where column was already removed

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0138_remove_ojtinfo_email'),
    ]

    operations = [
        # Use RunSQL to safely remove the email column if it exists
        # Migration 0138 already removed it, but this makes it safe to run
        migrations.RunSQL(
            sql="ALTER TABLE shared_ojtinfo DROP COLUMN IF EXISTS email;",
            reverse_sql="ALTER TABLE shared_ojtinfo ADD COLUMN IF NOT EXISTS email varchar(254);",
        ),
    ]
