# Generated by Django 5.2.3 on 2025-11-24 08:23
# Fixed: Use RunSQL with IF EXISTS to safely handle case where column/index was already removed

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0139_remove_ojtinfo_email'),
    ]

    operations = [
        # Use RunSQL to safely remove index and field if they exist
        # Previous migrations (0131, 0132, 0133, 0138, 0139) may have already removed these
        migrations.RunSQL(
            sql=[
                # Remove index if it exists (PostgreSQL compatible)
                "DROP INDEX IF EXISTS shared_ojti_email_5c6bf2_idx;",
                # Also try constraint format for PostgreSQL
                "ALTER TABLE shared_ojtinfo DROP CONSTRAINT IF EXISTS shared_ojti_email_5c6bf2_idx;",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE shared_ojtinfo DROP COLUMN IF EXISTS email;",
            reverse_sql="ALTER TABLE shared_ojtinfo ADD COLUMN IF NOT EXISTS email varchar(254);",
        ),
    ]
