# Generated by Django 5.2.3 on 2025-11-26 03:21
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0141_add_voucher_merchandise_to_reward_category'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ojtinfo',
            name='shared_ojti_email_5c6bf2_idx',
        ),
    ]