# Generated by Django 5.2.3 on 2025-11-27 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0143_preserve_claimed_rewards_on_item_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_event',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('deadline', 'Deadline'), ('event', 'Event'), ('reminder', 'Reminder'), ('holiday', 'Holiday'), ('meeting', 'Meeting'), ('announcement', 'Announcement')], default='event', max_length=20)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='shared.post')),
            ],
            options={
                'db_table': 'shared_calendarevent',
                'ordering': ['event_date', 'event_time'],
                'indexes': [models.Index(fields=['event_date', 'is_active'], name='shared_cale_event_d_41ad28_idx'), models.Index(fields=['created_by', 'event_date'], name='shared_cale_created_f9873d_idx'), models.Index(fields=['event_type', 'event_date'], name='shared_cale_event_t_76a079_idx')],
            },
        ),
    ]
