# Generated by Django 5.2.3 on 2025-12-13 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0144_remove_milestone_point_fields'),
        ('shared', '0147_add_gcash_receipt_to_reward_request'),
    ]

    operations = [
    ]
